version: '3.4'
services:
  droid:
    build:
      context: .
    container_name: api-droids
    ports:
      - "9090:9090"
    networks:
      - "dev"
    depends_on: 
      - "redis"
  redis:
    image: redis
    container_name: redis
    networks:
      - "dev"
    expose:
      - 6379
networks:
  dev:
    driver: bridge